apiVersion: v1
kind: Pod
metadata:
   name: exercise2
spec:
   containers:
     - name: nginx1
       image: nginx
       ports:
         - containerPort: 80
     - name: alpine1
       image: alpine
       args: 
         - sleep
         - 1d
      
              
apiVersion: v1
kind: Pod
metadata:
  name: exerc2
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    - name: alpine
      image: alpine
      args:
        - sleep
        - 1d