

apiVersion: v1
kind: Pod
metadata:
  name: spc
spec:
  containers:
    - name: spc
      image: sateeshreddy12/springpetclinic:1
      ports:
        - containerPort: 8080
----
apiVersion: v1
kind: Pod
metadata:
  name: nop
spec:
  containers:
    - name: nop
      image: sateeshreddy12/nopcommerce:latest
      ports:
        - containerPort: 5000
----
apiVersion: v1
kind: Pod
metadata:
  name: gol
spec:
  containers:
    - name: gol
      image: sateeshreddy12/gameoflife:latest
      ports:
        - containerPort: 8080
